"""
Trevor - UMAJA Autonomous Content Generation Agent

Trevor generates daily philosophical/technical articles about AI ethics,
autonomous systems, and Bahá'í-inspired principles.
"""

import os
import sys
import json
import argparse
from datetime import datetime
from pathlib import Path

# Add utils to path
sys.path.insert(0, str(Path(__file__).parent))

from utils.ethical_calculator import EthicalCalculator


class TrevorAgent:
    """
    Trevor - The Philosophical Content Generator
    
    Status: Active
    Purpose: Generate daily articles on AI ethics and autonomous systems
    Revenue: Content monetization through various channels
    """
    
    def __init__(self, test_mode: bool = False):
        """
        Initialize Trevor agent.
        
        Args:
            test_mode: If True, run in test mode without external API calls
        """
        self.test_mode = test_mode
        self.agent_name = "Trevor"
        self.version = "1.0.0"
        self.content_dir = Path(__file__).parent.parent / "content" / "articles"
        self.content_dir.mkdir(parents=True, exist_ok=True)
        
    def generate_article(self, day: int) -> dict:
        """
        Generate article content for a specific day.
        
        Args:
            day: Day number (1-365)
            
        Returns:
            Article data dictionary
        """
        topics = [
            "The Ethics of Autonomous AI Systems",
            "Bahá'í Principles in Modern Technology",
            "Universal Justice in Digital Economies",
            "Transparent Revenue Distribution Models",
            "AI Agents and Human Collaboration",
            "Voluntary Participation in Digital Communities",
            "The Future of Ethical Automation",
            "Building Trust in Autonomous Systems"
        ]
        
        # Cycle through topics
        topic_index = (day - 1) % len(topics)
        topic = topics[topic_index]
        
        article = {
            "title": f"{topic} - Day {day}",
            "day": day,
            "generated_at": datetime.now().isoformat(),
            "agent": self.agent_name,
            "version": self.version,
            "content": self._generate_content(topic, day),
            "metadata": {
                "word_count": 500,  # Placeholder
                "reading_time": "5 min",
                "category": "philosophy",
                "tags": ["AI", "ethics", "automation", "bahai"]
            }
        }
        
        return article
    
    def _generate_content(self, topic: str, day: int) -> str:
        """
        Generate article content.
        
        In production, this would call OpenAI API.
        For now, generates placeholder content.
        
        Args:
            topic: Article topic
            day: Day number
            
        Returns:
            Article content as markdown
        """
        if self.test_mode:
            return f"""# {topic}

## Introduction

This is a placeholder article generated by Trevor on day {day}.

In production, this would contain thoughtful analysis of {topic.lower()}, 
exploring the intersection of autonomous systems, ethical frameworks, 
and Bahá'í-inspired principles of justice and voluntary participation.

## Key Points

- Autonomous systems require ethical frameworks
- Voluntary participation ensures dignity
- Transparent revenue sharing builds trust
- Technology should serve humanity

## Conclusion

The future of autonomous systems depends on our commitment to ethical 
principles and transparent operations.

---

*Generated by Trevor v{self.version} - UMAJA Autonomous Agent*
*Day {day} - {datetime.now().strftime('%Y-%m-%d')}*
"""
        
        # In production: Call OpenAI API here
        # api_key = os.getenv('OPENAI_API_KEY')
        # response = openai.ChatCompletion.create(...)
        
        return f"[Production content would be generated here for: {topic}]"
    
    def save_article(self, article: dict) -> Path:
        """
        Save article to file system.
        
        Args:
            article: Article data dictionary
            
        Returns:
            Path to saved article file
        """
        date_str = datetime.now().strftime('%Y-%m-%d')
        filename = f"{date_str}-day-{article['day']}-trevor.md"
        filepath = self.content_dir / filename
        
        # Save markdown content
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(article['content'])
        
        # Save JSON metadata
        json_filepath = filepath.with_suffix('.json')
        with open(json_filepath, 'w', encoding='utf-8') as f:
            json.dump(article, f, indent=2)
        
        return filepath
    
    def log_execution(self, article: dict, filepath: Path, error: str = None) -> dict:
        """
        Log execution results.
        
        Args:
            article: Generated article data
            filepath: Path to saved article
            error: Error message if execution failed
            
        Returns:
            Log data dictionary
        """
        log_data = {
            "timestamp": datetime.now().isoformat(),
            "agent": self.agent_name,
            "version": self.version,
            "status": "error" if error else "success",
            "day": article.get('day') if article else None,
            "filepath": str(filepath) if filepath else None,
            "error": error,
            "test_mode": self.test_mode
        }
        
        # Log to console
        print(json.dumps(log_data, indent=2))
        
        return log_data
    
    def run(self, day: int = None) -> dict:
        """
        Main execution method.
        
        Args:
            day: Specific day to generate (default: day of year)
            
        Returns:
            Execution result dictionary
        """
        try:
            # Calculate day if not provided
            if day is None:
                day = datetime.now().timetuple().tm_yday
            
            print(f"🤖 Trevor Agent v{self.version} - Starting execution")
            print(f"📅 Generating content for day {day}")
            print(f"🧪 Test mode: {self.test_mode}")
            
            # Generate article
            article = self.generate_article(day)
            
            # Save article
            filepath = self.save_article(article)
            print(f"✅ Article saved to: {filepath}")
            
            # Calculate ethical allocation (example)
            calculator = EthicalCalculator()
            example_revenue = 100.0  # €100 from hypothetical content monetization
            allocation = calculator.calculate_allocation(example_revenue, user_opted_in=True)
            print(f"💰 Hypothetical revenue allocation: €{allocation['allocation']:.2f} to humanitarian causes")
            
            # Log execution
            log_data = self.log_execution(article, filepath)
            
            return {
                "success": True,
                "article": article,
                "filepath": str(filepath),
                "log": log_data
            }
            
        except Exception as e:
            error_msg = f"Error during execution: {str(e)}"
            print(f"❌ {error_msg}")
            log_data = self.log_execution(None, None, error=error_msg)
            
            return {
                "success": False,
                "error": error_msg,
                "log": log_data
            }


def main():
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        description='Trevor - UMAJA Autonomous Content Generation Agent'
    )
    parser.add_argument(
        '--day',
        type=int,
        help='Specific day to generate (1-365, default: current day of year)'
    )
    parser.add_argument(
        '--test',
        action='store_true',
        help='Run in test mode (no external API calls)'
    )
    
    args = parser.parse_args()
    
    # Create and run agent
    agent = TrevorAgent(test_mode=args.test)
    result = agent.run(day=args.day)
    
    # Exit with appropriate code
    sys.exit(0 if result['success'] else 1)


if __name__ == '__main__':
    main()
